// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Company _$$_CompanyFromJson(Map<String, dynamic> json) => _$_Company(
      symbol: json['Symbol'] as String,
      assetType: json['AssetType'] as String,
      name: json['Name'] as String,
      description: json['Description'] as String,
      cik: json['CIK'] as String,
      exchange: json['Exchange'] as String,
      currency: json['Currency'] as String,
      country: json['Country'] as String,
      sector: json['Sector'] as String,
      industry: json['Industry'] as String,
      address: json['Address'] as String,
      fiscalYearEnd: json['FiscalYearEnd'] as String,
      latestQuarter: json['LatestQuarter'] as String,
      marketCapitalization: json['MarketCapitalization'] as String,
      ebitda: json['EBITDA'] as String,
      peratio: json['PERatio'] as String,
      pegratio: json['PEGRatio'] as String,
      bookvalue: json['BookValue'] as String,
      dividendpershare: json['DividendPerShare'] as String,
      dividendYield: json['DividendYield'] as String,
      eps: json['EPS'] as String,
      revenuePerShareTTM: json['RevenuePerShareTTM'] as String,
      profitMargin: json['ProfitMargin'] as String,
      operatingMarginTTM: json['OperatingMarginTTM'] as String,
      returnOnAssetsTTM: json['ReturnOnAssetsTTM'] as String,
      returnOnEquityTTM: json['ReturnOnEquityTTM'] as String,
      revenueTTM: json['RevenueTTM'] as String,
      grossProfitTTM: json['GrossProfitTTM'] as String,
      dilutedEPSTTM: json['DilutedEPSTTM'] as String,
      quarterlyEarningsGrowthYOY: json['QuarterlyEarningsGrowthYOY'] as String,
      quarterlyRevenueGrowthYOY: json['QuarterlyRevenueGrowthYOY'] as String,
      analystTargetPrice: json['AnalystTargetPrice'] as String,
      trailingPE: json['TrailingPE'] as String,
      forwardPE: json['ForwardPE'] as String,
      priceToSalesRatioTTM: json['PriceToSalesRatioTTM'] as String,
      priceToBookRatio: json['PriceToBookRatio'] as String,
      evToRevenue: json['EVToRevenue'] as String,
      evToEBITDA: json['EVToEBITDA'] as String,
      beta: json['Beta'] as String,
      week52High: json['52WeekHigh'] as String,
      week52Low: json['52WeekLow'] as String,
      day50MovingAverage: json['50DayMovingAverage'] as String,
      day200MovingAverage: json['200DayMovingAverage'] as String,
      sharesOutstanding: json['SharesOutstanding'] as String,
      dividendDate: json['DividendDate'] as String,
      exDividendDate: json['ExDividendDate'] as String,
    );

Map<String, dynamic> _$$_CompanyToJson(_$_Company instance) =>
    <String, dynamic>{
      'Symbol': instance.symbol,
      'AssetType': instance.assetType,
      'Name': instance.name,
      'Description': instance.description,
      'CIK': instance.cik,
      'Exchange': instance.exchange,
      'Currency': instance.currency,
      'Country': instance.country,
      'Sector': instance.sector,
      'Industry': instance.industry,
      'Address': instance.address,
      'FiscalYearEnd': instance.fiscalYearEnd,
      'LatestQuarter': instance.latestQuarter,
      'MarketCapitalization': instance.marketCapitalization,
      'EBITDA': instance.ebitda,
      'PERatio': instance.peratio,
      'PEGRatio': instance.pegratio,
      'BookValue': instance.bookvalue,
      'DividendPerShare': instance.dividendpershare,
      'DividendYield': instance.dividendYield,
      'EPS': instance.eps,
      'RevenuePerShareTTM': instance.revenuePerShareTTM,
      'ProfitMargin': instance.profitMargin,
      'OperatingMarginTTM': instance.operatingMarginTTM,
      'ReturnOnAssetsTTM': instance.returnOnAssetsTTM,
      'ReturnOnEquityTTM': instance.returnOnEquityTTM,
      'RevenueTTM': instance.revenueTTM,
      'GrossProfitTTM': instance.grossProfitTTM,
      'DilutedEPSTTM': instance.dilutedEPSTTM,
      'QuarterlyEarningsGrowthYOY': instance.quarterlyEarningsGrowthYOY,
      'QuarterlyRevenueGrowthYOY': instance.quarterlyRevenueGrowthYOY,
      'AnalystTargetPrice': instance.analystTargetPrice,
      'TrailingPE': instance.trailingPE,
      'ForwardPE': instance.forwardPE,
      'PriceToSalesRatioTTM': instance.priceToSalesRatioTTM,
      'PriceToBookRatio': instance.priceToBookRatio,
      'EVToRevenue': instance.evToRevenue,
      'EVToEBITDA': instance.evToEBITDA,
      'Beta': instance.beta,
      '52WeekHigh': instance.week52High,
      '52WeekLow': instance.week52Low,
      '50DayMovingAverage': instance.day50MovingAverage,
      '200DayMovingAverage': instance.day200MovingAverage,
      'SharesOutstanding': instance.sharesOutstanding,
      'DividendDate': instance.dividendDate,
      'ExDividendDate': instance.exDividendDate,
    };
